#!/bin/bash

#Responavel por obter o CSV do fonte
wget https://app.dnpm.gov.br/DadosAbertos/SCM/Cessoes_de_Direitos.csv

#Converte os dados do CSV em ascii para eliminar possiveis caracteristicas de linguagens.
iconv -f iso-8859-15 -t ascii//translit Cessoes_de_Direitos.csv  > FCessoes_de_Direitos.csv
rm Cessoes_de_Direitos.csv 





